#!/usr/bin/env bash

export PLUGIN_COMMAND_PREFIX="uptime"
export PLUGIN_DATA_ROOT="/var/lib/dokku/data/uptime"
export PLUGIN_CONFIG_ROOT="/var/lib/dokku/config/uptime"
export KUMA_BIN="${PLUGIN_DATA_ROOT}/kuma"
export KUMA_CLI_VERSION="v2.0.0"
