#!/usr/bin/env bash

export PLUGIN_COMMAND_PREFIX="uptime"
export PLUGIN_DATA_ROOT="/var/lib/dokku/data/uptime"
export PLUGIN_CONFIG_ROOT="/var/lib/dokku/config/uptime"
export PLUGIN_DIR="${PLUGIN_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
export KUMA_BIN="${PLUGIN_DIR}/kuma-bin"
export KUMA_CLI_VERSION="v1.0.0"
